version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    build:
      context: ./airflow
    depends_on:
      - postgres
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH
      - AIRFLOW_UID=50000
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=Qebp1pURV8Vgw_rgstprkxgp8a1wxOvLbRxXC2x_N3I=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./datalake:/opt/airflow/datalake
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build:
      context: ./airflow
    depends_on:
      - postgres
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      - PATH=/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH
      - AIRFLOW_UID=50000
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=Qebp1pURV8Vgw_rgstprkxgp8a1wxOvLbRxXC2x_N3I=
    volumes:
      - ./dags:/opt/airflow/dags
      - ./etl:/opt/airflow/etl
      - ./datalake:/opt/airflow/datalake
    command: scheduler

volumes:
  postgres-db-volume:

